<a href="https://colab.research.google.com/github/hasanulazad-cloud/hasanul/blob/main/DS_Assignment_1%E2%80%94Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#Numpy Array Operations:

import numpy as np

# 1. Create a 1D NumPy Array:
# We represent daily temperatures for Week 1
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:\n", temperatures_w1)

# 2. Inspection and Properties
print("\nArray Properties")
print("Shape (rows, columns):", temperatures_w1.shape)
# (7,) means 1D array with 7 items
print("Data Type:", temperatures_w1.dtype)
# float64 means decimal numbers
print("Number of elements:", temperatures_w1.size)

# 3. Array Operations
# Convert all values to Fahrenheit
temperatures_w1_f = (temperatures_w1 * 9/5) + 32
print("\nTemperatures in Fahrenheit:\n", temperatures_w1_f)

# Quick statistics
print("Max Temp:", temperatures_w1.max())
print("Min Temp:", temperatures_w1.min())
print(f"Average Temp: {temperatures_w1.mean():.2f}")

# 4. Array Slicing and Indexing
print("\nSlicing Examples")
print("First three days:", temperatures_w1[0:3])
print("Weekend (last two days):", temperatures_w1[-2:]) # Negative means count from the end
print("Middle three days:", temperatures_w1[2:5])

# 5. Create a 2D Array (Matrix)
# Each row represents a different week
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Row 0: Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Row 1: Week 2
])
print("\n2D Array (Weeks 1 & 2):\n", temperatures)

# 6. Inspect and Slice 2D Array
print("\n2D Shape:", temperatures.shape) # (2, 7) -> 2 rows, 7 columns
# To slice 2D: array[row_slice, column_slice]
# ':' means 'all rows', and '-2:' means 'last two columns'
print("Weekends for both weeks:\n", temperatures[:, -2:])

Week 1 Temperatures:
 [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Array Properties
Shape (rows, columns): (7,)
Data Type: float64
Number of elements: 7

Temperatures in Fahrenheit:
 [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Max Temp: 26.1
Min Temp: 20.8
Average Temp: 23.54

Slicing Examples
First three days: [22.5 25.3 20.8]
Weekend (last two days): [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

2D Array (Weeks 1 & 2):
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

2D Shape: (2, 7)
Weekends for both weeks:
 [[24.8 21.9]
 [22.8 20.1]]


In [12]:
#Pandas Series:
import pandas as pd

#1. Creating a Pandas Series
marks_data = [95, 92, 89, 85, 80]
ranks_index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']

marks = pd.Series(data=marks_data, index=ranks_index)
print("Pandas Series:\n", marks)

# 2. Indexing and Slicing
print("\nAccessing Data")
print("1st rank student mark (position 0):", marks[0])
print("Top 3 ranks using .loc (label-based):\n", marks.loc[['Rank1', 'Rank2', 'Rank3']])
print("3rd rank student mark using .iloc (position-based):", marks.iloc[2])

# Filtering with a Boolean Mask
print("\nRanks with marks > 90:\n", marks[marks > 90])

# 3. Manipulating the Series
marks['Rank1'] = 100
# Modify a value
marks = marks.drop('Rank5')
# Delete an entry
cgpa = marks / 10
# Perform math on the whole Series

print("\nModified Series (CGPA):\n", cgpa)

Pandas Series:
 Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

Accessing Data
1st rank student mark (position 0): 95
Top 3 ranks using .loc (label-based):
 Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd rank student mark using .iloc (position-based): 89

Ranks with marks > 90:
 Rank1    95
Rank2    92
dtype: int64

Modified Series (CGPA):
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


/tmp/ipykernel_6933/1623202396.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st rank student mark (position 0):", marks[0])


In [13]:
#Pandas DataFrame:
import pandas as pd
# 1. Creating the Pandas DataFrame

data = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

# Turn the dictionary into a DataFrame table
transactions = pd.DataFrame(data)

# 2. Data Exploration

print("2. DATA EXPLORATION")

# Display the whole DataFrame
print("The Complete DataFrame:")
print(transactions)
print("-" * 40)

# Display head (first 5 rows) and tail (last 5 rows)
print("First 5 rows (head):")
print(transactions.head())
print("\nLast 5 rows (tail):")
print(transactions.tail())
print("-" * 40)

# Display basic information
print("Shape of DataFrame (Rows, Columns):", transactions.shape)
print("Column Names:", list(transactions.columns))
print("\nData Types of each column:")
print(transactions.dtypes)
print("-" * 40)

# Display only 'ProductCategory' and 'Amount' columns
print("Displaying specific columns:")
print(transactions[['ProductCategory', 'Amount']])
print("-" * 40)

# Retrieve the last 3 columns using .iloc
print("Last 3 columns of the DataFrame:")
print(transactions.iloc[:, -3:])
print("-" * 40)

# Filter rows: Region is 'North' AND Amount > 200
north_and_high_amount = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print("Rows where Region is North and Amount > 200:")
print(north_and_high_amount)
print("-" * 40)

# Find value counts for 'ProductCategory'
print("Count of each item in ProductCategory:")
print(transactions['ProductCategory'].value_counts())
print("-" * 40)

# Find unique values in 'Region' column
print("Unique regions in the data:")
print(transactions['Region'].unique())
print("-" * 40)

# Group by 'Region' and find the mean (average) amount for each region
print("Average Amount per Region:")
print(transactions.groupby('Region')['Amount'].mean())
print("\n" + "="*50 + "\n")

# 3. Manipulating the DataFrame
print("3. MANIPULATING THE DATAFRAME")

# Modify the 'Amount' for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("DataFrame after changing Transaction 102's Amount to 165:")
print(transactions.head(3))
# printing first few rows to check index position 1
print("-" * 40)

# Add a new column 'Discount' by calculating 10% (0.10) of the 'Amount'
transactions['Discount'] = transactions['Amount'] * 0.10
print("DataFrame after adding the 'Discount' column:")
print(transactions.head(3))
print("-" * 40)

# Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]
print("DataFrame after removing TransactionID 109:")
print(transactions.tail(3))
# printing the end rows to verify 109 is gone
print("-" * 40)

# Delete the 'Discount' column from the DataFrame
transactions.drop(columns=['Discount'], inplace=True)
print("Final DataFrame after deleting the 'Discount' column entirely:")
print(transactions.head(3))

2. DATA EXPLORATION
The Complete DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
----------------------------------------
First 5 rows (head):
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows (tail):
   TransactionID ProductCategory Region  Amount
5        