<a href="https://colab.research.google.com/github/hasanulazad-cloud/hasanul/blob/main/Module_3_Mathematics_and_Statistics_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from scipy import stats

# Task 1 – Linear Algebra Implementation
print("--- TASK 1: LINEAR ALGEBRA ---")

# Datasets
vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])
matrix_a = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])
matrix_b = np.array([
    [1, 2, 0],
    [3, 1, 4],
    [2, 5, 1]
])

# Vector operations
vec_add = vector_a + vector_b
vec_sub = vector_a - vector_b
vec_dot = np.dot(vector_a, vector_b)

print(f"Vector Addition: {vec_add}")
print(f"Vector Subtraction: {vec_sub}")
print(f"Vector Dot Product: {vec_dot}\n")

# Matrix operations
mat_add = matrix_a + matrix_b
mat_mul = np.dot(matrix_a, matrix_b)
# or matrix_a @ matrix_b

print(f"Matrix Addition:\n{mat_add}")
print(f"Matrix Multiplication:\n{mat_mul}\n")

# Determinant and Inverse
det_a = np.linalg.det(matrix_a)
print(f"Determinant of matrix_a: {det_a:.4f}")

if not np.isclose(det_a, 0):
    inv_a = np.linalg.inv(matrix_a)
    print(f"Inverse of matrix_a:\n{inv_a}\n")
else:
    print("Matrix_a is singular; inverse does not exist.\n")

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}\n")

--- TASK 1: LINEAR ALGEBRA ---
Vector Addition: [ 3  7 11]
Vector Subtraction: [1 1 1]
Vector Dot Product: 44

Matrix Addition:
[[3 3 3]
 [4 1 6]
 [6 6 2]]
Matrix Multiplication:
[[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]

Determinant of matrix_a: 6.0000
Inverse of matrix_a:
[[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]

Eigenvalues:
[ 5.54138127 -2.         -0.54138127]
Eigenvectors:
[[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]



In [2]:
# Task 2 – Probability Concepts
print("--- TASK 2: PROBABILITY CONCEPTS ---")

# 1. Probability of successful sales
sales_success = [0.65, 0.35]  # [Success, Failure]
print(f"Probability of successful sales: {sales_success[0]}")

# 2. Conditional probability demonstration
customer_segments = ["Premium", "Regular"]
segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}
print("Conditional Probabilities P(Purchase | Segment):")
for segment, prob in segment_purchase_probability.items():
    print(f"  P(Purchase | {segment}) = {prob}")

# 3. Bayes' Theorem
P_A = 0.40          # P(Premium)
P_B = 0.62          # P(Purchase)
P_B_given_A = 0.80  # P(Purchase | Premium)

# P(A|B) = [P(B|A) * P(A)] / P(B)
P_A_given_B = (P_B_given_A * P_A) / P_B
print(f"\nBayes' Theorem P(Premium | Purchase): {P_A_given_B:.4f}")

# 4. Binomial Distribution Simulation (20 trials, size=10 for demonstration)
n_trials = 20
success_prob = 0.65
binomial_sim = np.random.binomial(n=n_trials, p=success_prob, size=10)
print(f"\nBinomial Simulation (10 samples of 20 trials): {binomial_sim}")

# 5. Normal and Uniform Distributions (Generating 5 sample points each)
normal_mean = 50
normal_std = 10
uniform_low = 0
uniform_high = 1

normal_sim = np.random.normal(loc=normal_mean, scale=normal_std, size=5)
uniform_sim = np.random.uniform(low=uniform_low, high=uniform_high, size=5)

print(f"Normal Distribution samples: {normal_sim}")
print(f"Uniform Distribution samples: {uniform_sim}\n")

--- TASK 2: PROBABILITY CONCEPTS ---
Probability of successful sales: 0.65
Conditional Probabilities P(Purchase | Segment):
  P(Purchase | Premium) = 0.8
  P(Purchase | Regular) = 0.5

Bayes' Theorem P(Premium | Purchase): 0.5161

Binomial Simulation (10 samples of 20 trials): [17 12 12 12 14 13 14 11 12 12]
Normal Distribution samples: [32.60133694 55.0399752  59.93697136 56.60305255 57.27869067]
Uniform Distribution samples: [0.64458621 0.10445279 0.47654668 0.47405143 0.512414  ]



In [4]:
# Task 3 – Descriptive Statistics
print("--- TASK 3: DESCRIPTIVE STATISTICS ---")

sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
              190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

# Convert to Pandas Series for easy statistical calculations
df_sales = pd.Series(sales_data)

# Central Tendency
mean_val = df_sales.mean()
median_val = df_sales.median()
mode_val = df_sales.mode()[0]  # .mode() returns a Series

# Dispersion
data_range = df_sales.max() - df_sales.min()
variance_val = df_sales.var(ddof=0)  # Population variance
std_dev_val = df_sales.std(ddof=0)   # Population standard deviation

# Shape
skewness_val = df_sales.skew()
kurtosis_val = df_sales.kurt() # Pandas uses Fisher’s definition (excess kurtosis)

print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Mode: {mode_val}")
print(f"Range: {data_range}")
print(f"Variance: {variance_val:.2f}")
print(f"Standard Deviation: {std_dev_val:.2f}")
print(f"Skewness: {skewness_val:.4f}")
print(f"Kurtosis: {kurtosis_val:.4f}\n")

# Interpretation
print("--- INTERPRETATION ---")
print(f"The dataset has a skewness of {skewness_val:.4f}.")
if abs(skewness_val) < 0.1:
    print("Interpretation: The dataset is approximately symmetric.")
elif skewness_val > 0:
    print("Interpretation: The dataset is positively skewed (right-skewed).")
else:
    print("Interpretation: The dataset is negatively skewed (left-skewed).")

# Quick verification via Mean vs Median vs Mode
print(f"Context check (Mean: {mean_val}, Median: {median_val}, Mode: {mode_val})")

--- TASK 3: DESCRIPTIVE STATISTICS ---
Mean: 165.5
Median: 165.0
Mode: 135
Range: 90
Variance: 534.75
Standard Deviation: 23.12
Skewness: 0.0326
Kurtosis: -0.5493

--- INTERPRETATION ---
The dataset has a skewness of 0.0326.
Interpretation: The dataset is approximately symmetric.
Context check (Mean: 165.5, Median: 165.0, Mode: 135)
